### ISSUE TITLE
eagle2 + minimac4 for phasing and imputation?

### ISSUE THREAD

**Issue by Shicheng-Guo** [StahlKt/ImputationComparisonPaper2021#1]
I am wondering can you share a bash script/demo script to show eagle2 + minimac4 for phasing and imputation? Thanks.

**Comment by StahlKt** [comment]
Hi, 
there's not much to say, basically you have to format your dataset between vcf and the legend/hap format with bcftools inbetween phasing and imputation. I'll leave a link to bcftools, if you don't have it yet: https://samtools.github.io/bcftools/
This is how I used it in my routine, you might have to change some options to fit your purposes. 

for code: Do not put your files or filepaths in quotation marks, I just did it here so you know where to fill in your data.


Phasing with Eagle:
eagle --vcf  "input data in vcf" --outPrefix "Output Prefix"
                        --geneticMapFile "map file with column for chromosome"

to see all options for eagle, try ./eagle -h

change format for minimac4 with bcftools

bcftools convert --hapsample "input in vcf format"

(this worked for me, but you might want to add some specifications for the output. see the bcf tools documentation for that)


and then finally impute with IMPTUE4,

 impute4 -m "map file without(!) the column for chromosome" -h "reference panel in .hap format"
                    -l "input data .legend, should be the prefix you specified earlier, this might be gzipped"
                    -g "input data .haps, should be the prefix you specified earlier, this might be gzipped"
                    -int "start and stop position for your imputation"
                    -seed "set seed here (optional)"
                    -o "set output prefix"
                    -o_gz (optional, spefifies that your output should be gziped)
                    -maf_align (this or -no_maf_align, see IMPUTE4 user manual to see which one you want)

That's it, but I would advise you to parallelize the imputation by running several jobs with different start and end positions. You cannot meaningfully parallelize phasing, at least not that I know. 

Hope this helps!
